name: budget_wise
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: any
  http: ^1.2.2
  skeletonizer: ^1.4.3
  logger: ^2.4.0
  equatable: ^2.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: ^2.8.3
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  flutter_dotenv: ^5.2.1
  logging: ^1.3.0
  get_it: ^8.0.3
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/app/bg.png
    - assets/images/app/cool-background.svg
    - .env
